[general]
connection = "Data Source=KBNDVCRM80\\DEV01;Initial Catalog=RMM_MSCRM;Integrated Security=SSPI;TrustServerCertificate=True"
output = "MsCrm.fs"
namespace = "Rmm.Management.MsCrm"
cli_mutable = true
[readers]
reader_type = "Microsoft.Data.SqlClient.SqlDataReader"
[filters]
include = [
    "dbo/Contact*",
    "dbo/dgs_systemlogentry*",
    "dbo/ActivityP*",
    "dbo/SystemUser*",
    "dbo/WebResource*"
    ]
exclude = [
    "dbo/Filter*"
]
